In [5]:
import pandas as pd

In [6]:
# df1 = pd.read_csv(r"csv_files/explainDepression_final_dataset.csv")
df2 = pd.read_csv(r"csv_files/mental_health_combined_test.csv")
df3 = pd.read_csv(r"csv_files/Mental_Health_Condition_Classification.csv")
df4 = pd.read_csv(r"csv_files/mental_heath_feature_engineered.csv")
df5 = pd.read_csv(r"csv_files/mental_heath_unbanlanced.csv")
df6 = pd.read_csv(r"csv_files/Sentiment_Mental_health_dataset.csv")

In [ ]:
texts = pd.concat(
    [
        # df1["text"],
        df2["text"],
        df3["text"],
        df4["text"],
        df5["text"],
        df6["statement"],
    ],
    ignore_index=True
)

new_df = pd.DataFrame({"text": texts})

new_df = new_df.dropna(subset=["text"])
new_df = new_df[new_df["text"].str.strip() != ""]

new_df.to_csv("stories.csv", index=False)

                                                text
0  i don't understand whats wrong with me. i don'...
1  usually when i have anxiety just chatting with...
2  well, i've had anxiety and panic syndrome for ...
3  for the most minimal of things, like standing ...
4  i stay away from family and live with my roomm...

In [10]:
new_df.tail()

                                                     text
230049  Every time I have hope, something horrible hap...
230050  Intrusive thoughts (Call of the Void) Do your ...
230051  I've booked myself a haircut I think it's been...
230052  fitness noob help Hi guys, \n\nI'm a 26 year o...
230053  Im only 15 but I don’t think I’ll ever love my...